import './main.postcss'
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import { createI18n } from 'vue-i18n'

// import routes generated by Voie
import routes from 'voie-pages'
// import icons data generated by PurgeIcons
import '@purge-icons/generated'

import App from './App.vue'
import { messages } from './messages'

const app = createApp(App)
const router = createRouter({
  history: createWebHistory('/fixed-subtitles/'),
  routes
})

import UProgress from 'uprogress'
import 'uprogress/dist/uprogress.min.css'

const existentProgress = document.querySelector('.uprogress')
if (existentProgress) existentProgress.parentNode.removeChild(existentProgress)
const uProgress = new UProgress()

router.beforeResolve((to, from, next) => {
  if (to.name) {
    uProgress.start()
  }
  next()
})
router.afterEach(() => {
  setTimeout(() => uProgress.done(), 100)
})

const navigatorLanguages = navigator.languages || [navigator.language]
let locale

for (const language of navigatorLanguages) {
  if (messages[language]) {
    locale = language
    break
  }
  const reducedLang = language.substr(0, 2)
  if (messages[reducedLang]) {
    locale = reducedLang
    break
  }
}
if (!locale) locale = 'en'

const i18n = createI18n({
  locale,
  messages
})

app.use(i18n)
app.use(router)

app.mount('#app')
